// Some adapter targets are files the project already owns (AGENTS.md is shared with
// the repository's own agent guidance). MIDAS writes a delimited block into those
// files instead of overwriting them, so reinstalling is idempotent and never destroys
// a maintainer's own instructions.

export const MIDAS_BLOCK_START = '<!-- BEGIN MIDAS ADAPTER (generated by `midas install`; edits inside this block are overwritten) -->';
export const MIDAS_BLOCK_END = '<!-- END MIDAS ADAPTER -->';

export function renderMidasBlock(body) {
  return `${MIDAS_BLOCK_START}\n\n${body.trim()}\n\n${MIDAS_BLOCK_END}\n`;
}

/**
 * Return only the MIDAS-owned block from a shared file, or null when absent.
 * Contract validation uses this so a project's own AGENTS.md content is not
 * measured against MIDAS's size budget.
 */
export function extractMidasBlock(text) {
  const start = text.indexOf(MIDAS_BLOCK_START);
  if (start === -1) return null;
  const end = text.indexOf(MIDAS_BLOCK_END, start);
  if (end === -1) return null;
  return text.slice(start, end + MIDAS_BLOCK_END.length);
}

/**
 * Merge a MIDAS block into existing file content.
 * - empty/absent file  -> the block alone
 * - file with a block  -> block replaced in place, surrounding content preserved
 * - file without block -> block appended, existing content preserved
 */
export function mergeMidasBlock(existing, body) {
  const block = renderMidasBlock(body);
  if (!existing || !existing.trim()) return block;

  const start = existing.indexOf(MIDAS_BLOCK_START);
  const end = existing.indexOf(MIDAS_BLOCK_END, start === -1 ? 0 : start);
  if (start !== -1 && end !== -1) {
    const before = existing.slice(0, start);
    const after = existing.slice(end + MIDAS_BLOCK_END.length);
    return `${before}${block.trimEnd()}${after}`;
  }

  return `${existing.trimEnd()}\n\n${block}`;
}
