import fs from 'node:fs/promises';
import path from 'node:path';

function slugify(value) {
  return String(value ?? 'work-order')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'work-order';
}

function normalizePath(value) {
  return value.replaceAll('\\', '/');
}

function todayId() {
  return new Date().toISOString().slice(0, 10);
}

function prdText(objective, workOrder) {
  return `# PRD

Work Order: ${workOrder}
Objective: ${objective}
Status: draft

## Problem

- [ ] REQ-001: Define the user-facing problem in one concrete paragraph.

## Outcome

- [ ] REQ-002: Define the smallest useful outcome that can be verified locally.

## Functional Requirements

- [ ] REQ-003: Add the primary user workflow.
- [ ] REQ-004: Add the required data, file, or state inputs.
- [ ] REQ-005: Add the required output artifact or interface behavior.

## Non-Functional Requirements

- [ ] REQ-006: Add performance, reliability, privacy, and accessibility constraints that apply.

## Evidence Required

- [ ] REQ-007: Add tests, build checks, screenshots, logs, receipts, or human-review proof required before completion.

## Claim Ceiling

- [ ] REQ-008: State what remains UNKNOWN until provider, runtime, user, or human approval evidence exists.
`;
}

function designText(workOrder) {
  return `# DESIGN

Work Order: ${workOrder}
Status: draft

## Views

- View: Primary Surface

## Components

- Component: Work Order Header
- Component: Primary Action
- Component: Evidence Panel
- Component: Unknowns Panel

## Layout Constraints

- [ ] The first viewport shows the actual product/workflow, not a marketing placeholder.
- [ ] Text must not clip or overlap at mobile and desktop widths.
- [ ] State labels must distinguish verified, prototype, blocked, and UNKNOWN.
`;
}

function experienceText(workOrder) {
  return `# EXPERIENCE

Work Order: ${workOrder}
Status: draft

## Transition Map

- From: Work Order Header | Trigger: read objective | To: Evidence Panel
- From: Primary Surface | Trigger: open workspace | To: Work Order Header
- From: Primary Action | Trigger: user starts the task | To: Evidence Panel
- From: Evidence Panel | Trigger: check passes or fails | To: Unknowns Panel
- From: Unknowns Panel | Trigger: approval or blocked state | To: Work Order Header

## Human Approval States

- [ ] Identify steps that need human approval.
- [ ] Identify external, destructive, money-moving, or production actions.

## Failure Interventions

- [ ] Identify retry limits.
- [ ] Identify when the run must stop and preserve UNKNOWN.
`;
}

function readmeText(objective, workOrder) {
  return `# MIDAS Planning Packet

Work Order: ${workOrder}
Objective: ${objective}

Generated by \`midas plan\`.

## Files

- PRD.md: requirement source for verification-gap.
- DESIGN.md: structure source for UX spine.
- EXPERIENCE.md: behavior source for UX spine.

## Next Commands

\`\`\`bash
midas ux-spine --directory . --design .midas/planning/${workOrder}/DESIGN.md --experience .midas/planning/${workOrder}/EXPERIENCE.md
midas verify --directory . --spec .midas/planning/${workOrder}/PRD.md
\`\`\`

## Claim Ceiling

This packet is a planning scaffold. It is not implementation proof, runtime proof, provider proof, release proof, or public claim approval.
`;
}

export async function createPlanningPacket(options = {}) {
  const target = path.resolve(options.directory ?? '.');
  const objective = options.objective ?? options._objective ?? 'Define one scoped MIDAS work order';
  const workOrder = slugify(options['work-order'] ?? options.workOrder ?? `${todayId()}-${objective}`);
  const outDir = path.join(target, '.midas', 'planning', workOrder);
  await fs.mkdir(outDir, { recursive: true });
  const files = [
    ['PRD.md', prdText(objective, workOrder)],
    ['DESIGN.md', designText(workOrder)],
    ['EXPERIENCE.md', experienceText(workOrder)],
    ['README.md', readmeText(objective, workOrder)]
  ];
  const written = [];
  for (const [name, text] of files) {
    const file = path.join(outDir, name);
    await fs.writeFile(file, text);
    written.push(normalizePath(path.relative(target, file)));
  }
  return {
    status: 'created',
    target,
    workOrder,
    objective,
    files: written,
    next: [
      `midas ux-spine --directory . --design .midas/planning/${workOrder}/DESIGN.md --experience .midas/planning/${workOrder}/EXPERIENCE.md`,
      `midas verify --directory . --spec .midas/planning/${workOrder}/PRD.md`
    ]
  };
}
